import { ROOT_SITEMAP_CACHE_HEADERS, setDocsCacheHeaders } from "@/proxy";

// Root-domain sitemap. Hosted repos each get a generated sitemap at
// /{owner}/{repo}/sitemap.xml (see buildDocsRepoSitemapXml); this covers the
// marketing site itself. The homepage is currently the only root-level HTML
// page — add entries here if more root pages are introduced. XML shape
// matches the per-repo sitemaps generated by the `sitemap` package.
const SITEMAP_XML = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://docs.page/</loc>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>
</urlset>
`;

export function GET() {
  const response = new Response(SITEMAP_XML, {
    headers: {
      "Content-Type": "application/xml; charset=utf-8",
    },
  });
  setDocsCacheHeaders(response.headers, ROOT_SITEMAP_CACHE_HEADERS);
  return response;
}
