name: website

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: NPM Install
        run: yarn
      - name: Check Linting
        run: yarn run check:linting
      - name: Check Formatting
        run: yarn run check:formatting
      - name: Check TS Compiles
        run: yarn run check:typescript
      - name: Check Spelling & Grammar
        run: yarn run check:spelling
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: NPM Install
        run: yarn
      - name: Jest Tests
        run: yarn run test
